### ISSUE TITLE
Bug -  NullInjectorError: No provider for ChangeDetectorRef!

### ISSUE THREAD

**Issue by rbalet** [ChristianKohler/ng-resize-observer#8]
I've tried to use this library, but got the following error

 NullInjectorError: No provider for ChangeDetectorRef!
 
 ```
 ERROR NullInjectorError: R3InjectorError(MegaphonePageHeaderModule)[NgResizeObserver -> ResizeObserverService -> ChangeDetectorRef -> ChangeDetectorRef -> ChangeDetectorRef -> ChangeDetectorRef -> ChangeDetectorRef]: 
  NullInjectorError: No provider for ChangeDetectorRef!
    at NullInjector.get (vendor.js:91419:21)
    at R3Injector.get (vendor.js:91841:27)
    at R3Injector.get (vendor.js:91841:27)
    at R3Injector.get (vendor.js:91841:27)
    at R3Injector.get (vendor.js:91841:27)
    at R3Injector.get (vendor.js:91841:27)
    at injectInjectorOnly (vendor.js:84743:29)
    at Module.ɵɵinject (vendor.js:84747:59)
    at Object.ResizeObserverService_Factory [as factory] (default-projects_website_src_lib_shared_layouts_megaphone-layout-page_megaphone-layout-page_m-e4f250.js:1980:97)
    at R3Injector.hydrate
 ```
 
 this is the error about the `ResizeObserverService_Factory`
 ```
 ResizeObserverService.ɵfac = function ResizeObserverService_Factory(t) {
  return new (t || ResizeObserverService)(_angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵinject"](_angular_core__WEBPACK_IMPORTED_MODULE_1__.ChangeDetectorRef), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵinject"](_angular_core__WEBPACK_IMPORTED_MODULE_1__.ElementRef, 8), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵinject"](RESIZE_OBSERVER));
};
```

I've imported the service like follow in my `component..module.ts`

```
import { ngResizeObserverProviders } from 'ng-resize-observer'
// ...
providers: [ngResizeObserverProviders],
```

**Comment by rbalet** [comment]
Adding it inside the `providers` from the `@Component` fixed the issue, sorry for the false flag
